services:
  pokeroulette-api:
    image: git.cubiss.cz/cubiss/pokeroulette:latest
    environment:
      JWT_SECRET: "change-me-to-a-random-secret-at-least-32-chars"
      ALLOWED_ORIGINS: "*"
      ENABLE_DOCS: "false"
    volumes:
      - ./server/data:/app/data
    ports:
      - "8080:8080"
